travis:
  secure:
    BINSTAR_TOKEN: SnX+pgSWUzpEMmtv5gLfXqB9BAdHC1XubBogC3NEzBBjL4XAVhK1WzCyoWhOeg3XvQEAqdNtyNtXHQiYCT6PY4PAbSKsWoaHLpU70Tv3vuSKi/6jVkPtl3PdRmx2mITtfKb86muGGGo7BFMH9xxvF5IWhOfyyKujycBMT7TNW4+CP75wUcir8MEBiduecHNJULuGwbZOAZZhjliaoYz+2tVRoXlk4zBROfCLchza55kE24b3hlM7BI+Ns34dP9+4IcM+1QFv/fnq3HrCB0+AkW6UTptN/VuEwoFuIuAz3uvMStv0+d+ujp4eEpmaMiiPSCF9ct2jvrZo1/GgzfkZKPl8tXIG6Q/eFSba9CXkY06ZU0ij5v5SX7PRlLnocDJdn0t/eOWMrnJASqiZ6mJpm04p0w3qa2rkiA1BqnHtD5Ed23T4RURZM0xSfB9SCr0So6vRkexCU9LM+W2d+9M98vsYnj75a2gxWZvhBTQpIYvap2LtA+eXfbr+9aR9MUe5wyAMxHt2pEx+zSYDDn5S0wOZ7iefZGAu16TKVhYxmiels6AY7QW2dy+61PDbVGv/3RYzVVaW3y338Jbw0aYVsWTn1AzmnyZAfvtQcAcfIz1GjMMa2a/uUk7+6kq44plFyr3u+6+D0bKNgweuzvRFGCaLqaFZnC3nlRdJwv859uc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
